name: Build Kernel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-arm64

      - name: Download toolchain
        run: |
          git clone --depth=1 https://github.com/arter97/arm64-gcc.git gcc
          export PATH=$PWD/gcc/bin:$PATH

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make <你的_defconfig>
          make -j$(nproc)
          
      # 可选：上传编译产物
      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: KernelImage
          path: out/arch/arm64/boot/Image.gz-dtb
